import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic'
import Grid from '@mui/material/Grid'
import 'leaflet/dist/leaflet.css'

import FileUpload from '../src/components/FileUpload'
import DataTable from '../src/components/DataTable'


/* const MapSelect = dynamic(import('../components/MapSelect'), {
  ssr: false,
  loading: () => (
    <div style={{textAlign: 'center', paddingTop: 20}}>
      Loading...
    </div>
  )
}) */



export default function Home() {
  const [data, setData] = useState()

  const MapSelect = dynamic(
    () => import('../src/components/MapSelect'),
    {
      loading: () => <p>A map is loading</p>,
      ssr: false
    }
  )

  const Map = dynamic(
    () => import('../src/components/Map'), 
    { ssr: false }
  )
  console.log(process.env.MAPBOX_API_KEY)

  return (
    <div>
      <Head>
        <title>Farm Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solita.png" />
      </Head>

      <Grid 
        container
        direction='row'
        justifyContent="center"
        alignItems="center"
        minHeight="650px"
        >
        <Grid item xs={6}> 
          <Grid container alignItems="end" justifyContent="center">
            <Map />
            <FileUpload setData={setData} />
          </Grid>
        </Grid>
        <Grid item xs={6}>
          {data && <DataTable data={data} />}
        </Grid>
      </Grid>
      
    </div>
  )
}
