import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Button from '@mui/material/Button'

import FileUpload from '../src/components/FileUpload'
import DataTable from '../src/components/DataTable'

import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FileUpload setData={setData} />
      {data && <DataTable data={data} />}
      
    </div>
  )
}
